"""
Django settings for projetAvocat project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
import mimetypes

mimetypes.add_type("text/css", ".css", True)
mimetypes.add_type("application/javascript", ".js", True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-%q=1h_ia#7k2+m92+5dy=_w2ctl_^ts=4j#foz_ea#pvx-p$i$')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*'] # Permet toutes les adresses sur Railway
CSRF_TRUSTED_ORIGINS = ['https://*.railway.app'] # Autorise les domaines Railway pour la sécurité des formulaires




# Application definition

INSTALLED_APPS = [
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'consultation',  # Notre application principale
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Pour les fichiers statiques en ligne
    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'projetAvocat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Les templates sont dans consultation/templates/ (trouvés via APP_DIRS=True)
        'DIRS': [BASE_DIR / 'consultation' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'consultation.context_processors.site_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'projetAvocat.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database logic using dj-database-url (Automatic for Railway)
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(default=DATABASE_URL, conn_max_age=600)
    }
else:
    # Si on est sur Railway (détecté par la présence de RAILWAY_ENVIRONMENT) mais sans DATABASE_URL
    if os.environ.get('RAILWAY_ENVIRONMENT'):
         raise Exception("ERREUR CRITIQUE : La variable DATABASE_URL est manquante dans Railway ! Reliez la base de données au service Web.")
    
    # Fallback pour le développement local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'avocat',
            'USER': 'postgres',
            'PASSWORD': '3432',
            'HOST': '127.0.0.1',
            'PORT': '5432',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Remplace l'ancienne# Redirection automatique vers le login personnalisé
LOGIN_URL = 'admin_login'
# 1. L'URL de base pour accéder aux fichiers (ne pas oublier le slash à la fin)
STATIC_URL = 'static/'

# 2. Le chemin physique vers ton dossier static
# D'après ton arbre, le dossier est à la racine de "projetAvocat"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# 3. (Optionnel pour le moment mais utile) Où Django regroupera les fichiers en production
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuration des redirections
LOGIN_REDIRECT_URL = 'admin_dashboard'  # Redirection après connexion réussie
LOGOUT_REDIRECT_URL = 'index'           # Redirection après déconnexion
LOGIN_URL = 'admin_login'               # Page de connexion si l'utilisateur n'est pas authentifié
