# Generated by Django 5.2.8 on 2026-03-23 23:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('domaine', models.CharField(choices=[('FONCIER', 'Foncier et Immobilier'), ('FAMILLE', 'Droit de la Famille'), ('TRAVAIL', 'Droit du Travail'), ('AFFAIRES', 'Droit des Affaires')], default='FONCIER', max_length=20)),
                ('description', models.TextField(verbose_name='Description du service')),
                ('statut', models.CharField(choices=[('ATTENTE', 'En attente'), ('EN_COURS', 'Service en cours de traitement'), ('TERMINE', 'Cas terminé / Archivé')], default='ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_actuel', models.CharField(choices=[('LIGHT', 'Mode Clair'), ('DARK', 'Mode Sombre')], default='LIGHT', max_length=10)),
                ('nom_cabinet', models.CharField(default='FOYAK TOGO', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_audience', models.DateTimeField()),
                ('lieu', models.CharField(default='Tribunal de Lomé', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='consultation.demandeservice')),
            ],
        ),
    ]
