# Generated by Django 5.2.8 on 2026-03-29 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='theme_actuel',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur Technique'), ('AVOCAT', 'Avocat')], default='AVOCAT', max_length=10)),
                ('theme_pref', models.CharField(choices=[('LIGHT', 'Mode Clair'), ('DARK', 'Mode Sombre')], default='LIGHT', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Audience',
        ),
    ]
